### ISSUE TITLE
No resources are deployed

### ISSUE THREAD

**Issue by jachinte** [AbdelrhmanHamouda/locust-k8s-operator#31]
**Describe the bug**
No jobs or services are run when I deploy a LocustTest.

**To Reproduce**
1. Create a local kubernetes cluster using [k3d](https://k3d.io):
```
k3d cluster create mycluster
```
2. Deploy the Helm chart of the operator:
```
cd locust-k8s-operator/charts/locust-k8s-operator
helm install -f values.yaml locust-operator . -n locust-operator --create-namespace --debug --wait
```
3. Create a ConfigMap:
```
kubectl create configmap demo-cm --from-file PATH_TO_FILE/demo.py
```
5. Create and deploy the LocustTest specification:
```
cat <<EOF >test.yaml
apiVersion: locust.io/v1
kind: LocustTest
metadata:
  name: demo.test
spec:
  image: locustio/locust:latest
  masterCommandSeed:
    --locustfile /lotest/src/demo.py
    --host https://www.google.com
    --users 100
    --spawn-rate 3
    --run-time 3m
  workerCommandSeed: --locustfile /lotest/src/demo.py
  workerReplicas: 3
  configMap: demo-cm
EOF

kubectl apply -f test.yaml
```

**Expected behavior**
I would expect to see two jobs and one service but I see none. Although I do see the locusttest resource and the operator.

**Screenshots**
```
# kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   45h

# kubectl get job
No resources found in default namespace.

# kubectl get locusttest
NAME        MASTER_CMD                                                                                                         WORKER_REPLICA_COUNT   IMAGE                    AGE
demo.test   --locustfile /lotest/src/robot-shop.py --host http://35.237.9.210:8080/ --users 100 --spawn-rate 3 --run-time 3m   3                      locustio/locust:latest   9m2s

# kubectl get all -n locust-operator
NAME                                                       READY   STATUS    RESTARTS       AGE
pod/locust-operator-locust-k8s-operator-56d88bfcc4-zbgpx   1/1     Running   1 (118m ago)   120m

NAME                                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/locust-operator-locust-k8s-operator   1/1     1            1           120m

NAME                                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/locust-operator-locust-k8s-operator-56d88bfcc4   1         1         1       120m
```

**Additional context**
```
# helm list -n locust-operator
NAME           	NAMESPACE      	REVISION	UPDATED                             	STATUS  	CHART                    	APP VERSION
locust-operator	locust-operator	1       	2022-10-17 15:53:09.454928 -0400 EDT	deployed	locust-k8s-operator-0.1.0	0.1.0
```

Here are the logs, which contain more detail about the problem:

<details>
<pre>
# kubectl logs pod/locust-operator-locust-k8s-operator-56d88bfcc4-zbgpx -n locust-operator
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.6.2)

2022-10-17 19:54:53,983 INFO  [main] io.micronaut.context.env.DefaultEnvironment: Established active environments: [k8s, cloud]
2022-10-17 19:54:56,958 INFO  [main] com.locust.LocustTestOperatorStarter: Starting Kubernetes reconciler!
2022-10-17 19:54:58,361 WARN  [main] io.javaoperatorsdk.operator.api.config.BaseConfigurationService: Configuration for reconciler 'locusttestreconciler' was not found. Known reconcilers: None.
2022-10-17 19:54:58,366 INFO  [main] io.javaoperatorsdk.operator.api.config.BaseConfigurationService: Created configuration for reconciler com.locust.operator.controller.LocustTestReconciler with name locusttestreconciler
2022-10-17 19:54:58,544 INFO  [main] io.javaoperatorsdk.operator.Operator: Registered reconciler: 'locusttestreconciler' for resource: 'class com.locust.operator.customresource.LocustTest' for namespace(s): [all namespaces]
2022-10-17 19:54:58,545 INFO  [main] io.javaoperatorsdk.operator.Operator: Operator SDK 3.2.0 (commit: edd12e5) built on Mon Sep 05 08:26:50 UTC 2022 starting...
2022-10-17 19:54:58,574 INFO  [main] io.javaoperatorsdk.operator.Operator: Client version: 6.1.1
2022-10-17 19:54:58,580 INFO  [main] io.javaoperatorsdk.operator.processing.Controller: Starting 'locusttestreconciler' controller for reconciler: com.locust.operator.controller.LocustTestReconciler, resource: com.locust.operator.customresource.LocustTest
2022-10-17 19:54:59,547 INFO  [main] io.javaoperatorsdk.operator.processing.Controller: 'locusttestreconciler' controller started, pending event sources initialization
2022-10-17 19:54:59,614 INFO  [main] io.micronaut.runtime.Micronaut: Startup completed in 7597ms. Server Running: http://locust-operator-locust-k8s-operator-56d88bfcc4-zbgpx:8080
2022-10-17 21:42:36,550 INFO  [ReconcilerExecutor-locusttestreconciler-39] com.locust.operator.controller.LocustTestReconciler: LocustTest created: 'demo.test'
2022-10-17 21:42:36,601 INFO  [ReconcilerExecutor-locusttestreconciler-39] com.locust.operator.controller.utils.resource.manage.ResourceCreationManager: Creating service for: demo-test-master in namespace: default
2022-10-17 21:42:36,894 ERROR [ReconcilerExecutor-locusttestreconciler-39] com.locust.operator.controller.utils.resource.manage.ResourceCreationManager: Exception occurred during service creation: Failure executing: POST at: https://10.43.0.1/api/v1/namespaces/default/services. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. services is forbidden: User "system:serviceaccount:locust-operator:locust-operator-locust-k8s-operator" cannot create resource "services" in API group "" in the namespace "default".
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.43.0.1/api/v1/namespaces/default/services. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. services is forbidden: User "system:serviceaccount:locust-operator:locust-operator-locust-k8s-operator" cannot create resource "services" in API group "" in the namespace "default".
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:713)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:693)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:642)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:581)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$retryWithExponentialBackoff$2(OperationSupport.java:622)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$4.onResponse(OkHttpClientImpl.java:268)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-10-17 21:42:36,934 INFO  [ReconcilerExecutor-locusttestreconciler-39] com.locust.operator.controller.utils.resource.manage.ResourceCreationManager: Creating Job for: demo-test-master in namespace: default
2022-10-17 21:42:37,880 ERROR [ReconcilerExecutor-locusttestreconciler-39] com.locust.operator.controller.utils.resource.manage.ResourceCreationManager: Exception occurred during Job creation: Failure executing: POST at: https://10.43.0.1/apis/batch/v1/namespaces/default/jobs. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. jobs.batch is forbidden: User "system:serviceaccount:locust-operator:locust-operator-locust-k8s-operator" cannot create resource "jobs" in API group "batch" in the namespace "default".
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.43.0.1/apis/batch/v1/namespaces/default/jobs. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. jobs.batch is forbidden: User "system:serviceaccount:locust-operator:locust-operator-locust-k8s-operator" cannot create resource "jobs" in API group "batch" in the namespace "default".
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:713)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:693)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:642)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:581)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$retryWithExponentialBackoff$2(OperationSupport.java:622)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$4.onResponse(OkHttpClientImpl.java:268)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-10-17 21:42:37,917 INFO  [ReconcilerExecutor-locusttestreconciler-39] com.locust.operator.controller.utils.resource.manage.ResourceCreationManager: Creating Job for: demo-test-worker in namespace: default
2022-10-17 21:42:37,997 ERROR [ReconcilerExecutor-locusttestreconciler-39] com.locust.operator.controller.utils.resource.manage.ResourceCreationManager: Exception occurred during Job creation: Failure executing: POST at: https://10.43.0.1/apis/batch/v1/namespaces/default/jobs. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. jobs.batch is forbidden: User "system:serviceaccount:locust-operator:locust-operator-locust-k8s-operator" cannot create resource "jobs" in API group "batch" in the namespace "default".
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.43.0.1/apis/batch/v1/namespaces/default/jobs. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. jobs.batch is forbidden: User "system:serviceaccount:locust-operator:locust-operator-locust-k8s-operator" cannot create resource "jobs" in API group "batch" in the namespace "default".
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:713)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:693)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:642)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:581)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$retryWithExponentialBackoff$2(OperationSupport.java:622)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$4.onResponse(OkHttpClientImpl.java:268)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
</pre>
</details>

**Comment by jachinte** [comment]
By the way, this is a great project! I've been looking for a project like this and all alternatives seem outdated and abandoned. One feature you're implementing caught my eye: the possibility of importing additional metrics to the metrics endpoint, if I understood correctly. How are you thinking of implementing this feature?

One thing that I'd like to implement is the possibility of adding labels to the test pods, so that Prometheus can do things with them, like using labels to differentiate between tests, or do multi-tenant monitoring using Cortex. Would you be interested in having that as a contribution?

**Comment by jachinte** [comment]
I just realized that the problem I'm describing was happening because I was deploying the resources to namespace `default`. When I deploy to `locust-operator` it works well. I'm assuming this is the default behaviour, so I'm closing the issue.

I did commit my changes to [jachinte/locust-k8s-operator](https://github.com/jachinte/locust-k8s-operator) (branch `feat/labels`), in case you're interested in the pod-labelling feature.

**Comment by jachinte** [comment]
@AbdelrhmanHamouda The new documentation site is beautiful! My mistake was installing the Helm chart within its own namespace, and then deploying the tests in the `default` namespace.

I will think about the external metrics part and when I have a more concrete idea, I will open the issue. In my case, importing metrics is done on a per test basis because each test can target a different system.
